---
title: "Session 3"
output: html_notebook
---


```{r}
library(tidyverse)
```


```{r}
(books <- BX_Books %>%
  select(ISBN, `Book-Title`, `Book-Author`, `Year-Of-Publication`, `Publisher`) %>%
  filter(`Year-Of-Publication` > 0, `Year-Of-Publication` <= 2020, grepl("^[0-9Xx]+$", ISBN, )))
```

```{r}
(ratings <- BX_Book_Ratings %>%
  inner_join(books) %>%
   filter(!is.na(`Book-Title`)))
```

```{r}
(users <- BX_Users %>%
   filter(!is.na(Age)) %>%
   filter(`Age` < 100 | `Age` > 6))
```



```{r}
(all <- ratings %>%
   left_join(users) %>%
   mutate(country = str_remove(Location,".*,")) %>%
   filter(country != "") %>%
   select(-Location))
```


```{r}
write_csv(all, "all.csv")
```




```{r}
library(tidyverse)
library(arules)
library(arulesViz)
```


```{r}
all <- read_csv("all.csv") %>%
  filter(`Book-Rating` > 6)
```


```{r message=FALSE}
i <- split(all$`Book-Title`,all$`User-ID`)
txn <- as(i, "transactions")
basket_rules <- apriori(txn, parameter = list(sup = 0.0015, conf = 0.001, minlen=2, target="rules"))
```



```{r}
myRules_Direct <- as(basket_rules, "data.frame")
basket_rules_hi <- head(basket_rules, by ="lift",100)
head(myRules_Direct, 20)
```


```{r}
plot(basket_rules_hi, method="graph", main="Books")
```


```{r}
plot(basket_rules_hi, method="graph", main="Books", engine="interactive")
```


